# push(main/master) を有効化。pull_request は secrets ポリシー確認後に追加する。
# 非Rustリポジトリで誤配布された場合は、Cargo.toml 未検出時に各ステップを成功スキップする。
when:
  - event: [push]
    branch: [main, master]

steps:
  - name: fmt
    image: rust:1
    commands:
      - |
        set -eu
        if [ ! -f Cargo.toml ]; then
          echo "Cargo.toml not found. Skip fmt."
          exit 0
        fi
        if [ -f rust-toolchain.toml ]; then
          toolchain="$(sed -nE 's/^[[:space:]]*channel[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' rust-toolchain.toml | head -n 1)"
        elif [ -f rust-toolchain ]; then
          toolchain="$(head -n 1 rust-toolchain | tr -d '[:space:]')"
        else
          toolchain=""
        fi
        if [ -n "${toolchain}" ]; then
          rustup toolchain install "${toolchain}" --profile minimal
          rustup default "${toolchain}"
        else
          echo "rust-toolchain* not found. Use rust:1 (stable)."
        fi
      - rustup component add rustfmt
      - cargo fmt --check

  - name: clippy
    image: rust:1
    commands:
      - |
        set -eu
        if [ ! -f Cargo.toml ]; then
          echo "Cargo.toml not found. Skip clippy."
          exit 0
        fi
        if [ -f rust-toolchain.toml ]; then
          toolchain="$(sed -nE 's/^[[:space:]]*channel[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' rust-toolchain.toml | head -n 1)"
        elif [ -f rust-toolchain ]; then
          toolchain="$(head -n 1 rust-toolchain | tr -d '[:space:]')"
        else
          toolchain=""
        fi
        if [ -n "${toolchain}" ]; then
          rustup toolchain install "${toolchain}" --profile minimal
          rustup default "${toolchain}"
        else
          echo "rust-toolchain* not found. Use rust:1 (stable)."
        fi
      - rustup component add clippy
      - cargo clippy -- -D warnings

  - name: test
    image: rust:1
    commands:
      - |
        set -eu
        if [ ! -f Cargo.toml ]; then
          echo "Cargo.toml not found. Skip test."
          exit 0
        fi
        if [ -f rust-toolchain.toml ]; then
          toolchain="$(sed -nE 's/^[[:space:]]*channel[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' rust-toolchain.toml | head -n 1)"
        elif [ -f rust-toolchain ]; then
          toolchain="$(head -n 1 rust-toolchain | tr -d '[:space:]')"
        else
          toolchain=""
        fi
        if [ -n "${toolchain}" ]; then
          rustup toolchain install "${toolchain}" --profile minimal
          rustup default "${toolchain}"
        else
          echo "rust-toolchain* not found. Use rust:1 (stable)."
        fi
      - cargo test

  - name: build-release
    image: rust:1
    commands:
      - |
        set -eu
        if [ ! -f Cargo.toml ]; then
          echo "Cargo.toml not found. Skip build-release."
          exit 0
        fi
        if [ -f rust-toolchain.toml ]; then
          toolchain="$(sed -nE 's/^[[:space:]]*channel[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' rust-toolchain.toml | head -n 1)"
        elif [ -f rust-toolchain ]; then
          toolchain="$(head -n 1 rust-toolchain | tr -d '[:space:]')"
        else
          toolchain=""
        fi
        if [ -n "${toolchain}" ]; then
          rustup toolchain install "${toolchain}" --profile minimal
          rustup default "${toolchain}"
        else
          echo "rust-toolchain* not found. Use rust:1 (stable)."
        fi
      - cargo build --release
